//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.GPShamanWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GPShamanWS.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistanciaTiempo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDistanciaTiempo(string latMov, string lngMov, string latDst, string lngDst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistanciaTiempo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDistanciaTiempoAsync(string latMov, string lngMov, string latDst, string lngDst);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDireccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDireccion(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDireccion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDireccionAsync(string lat, string lng);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatLong", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetLatLong(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatLong", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetLatLongAsync(string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPuntosEnPoligono", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPuntosEnPoligono(float pLat, float pLon, string pTip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPuntosEnPoligono", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPuntosEnPoligonoAsync(float pLat, float pLon, string pTip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIncidente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getIncidente(string cod, string fec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getIncidente", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getIncidenteAsync(string cod, string fec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSerialSetLog(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLog", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSerialSetLogAsync(string serialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLogLast", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getSerialSetLogLast(string serialNumber, int pRemote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSerialSetLogLast", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getSerialSetLogLastAsync(string serialNumber, int pRemote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isInGestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string isInGestion(string user, string pass, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isInGestion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> isInGestionAsync(string user, string pass, string llave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPushNotification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool setPushNotification(string licencia, string nroMovil, string mensaje, string appID, string restApiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setPushNotification", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> setPushNotificationAsync(string licencia, string nroMovil, string mensaje, string appID, string restApiKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : DataAccess.GPShamanWS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<DataAccess.GPShamanWS.ServiceSoap>, DataAccess.GPShamanWS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDistanciaTiempo(string latMov, string lngMov, string latDst, string lngDst) {
            return base.Channel.GetDistanciaTiempo(latMov, lngMov, latDst, lngDst);
        }
        
        public System.Threading.Tasks.Task<string> GetDistanciaTiempoAsync(string latMov, string lngMov, string latDst, string lngDst) {
            return base.Channel.GetDistanciaTiempoAsync(latMov, lngMov, latDst, lngDst);
        }
        
        public string GetDireccion(string lat, string lng) {
            return base.Channel.GetDireccion(lat, lng);
        }
        
        public System.Threading.Tasks.Task<string> GetDireccionAsync(string lat, string lng) {
            return base.Channel.GetDireccionAsync(lat, lng);
        }
        
        public string GetLatLong(string direccion) {
            return base.Channel.GetLatLong(direccion);
        }
        
        public System.Threading.Tasks.Task<string> GetLatLongAsync(string direccion) {
            return base.Channel.GetLatLongAsync(direccion);
        }
        
        public string GetPuntosEnPoligono(float pLat, float pLon, string pTip) {
            return base.Channel.GetPuntosEnPoligono(pLat, pLon, pTip);
        }
        
        public System.Threading.Tasks.Task<string> GetPuntosEnPoligonoAsync(float pLat, float pLon, string pTip) {
            return base.Channel.GetPuntosEnPoligonoAsync(pLat, pLon, pTip);
        }
        
        public string getIncidente(string cod, string fec) {
            return base.Channel.getIncidente(cod, fec);
        }
        
        public System.Threading.Tasks.Task<string> getIncidenteAsync(string cod, string fec) {
            return base.Channel.getIncidenteAsync(cod, fec);
        }
        
        public string getSerialSetLog(string serialNumber) {
            return base.Channel.getSerialSetLog(serialNumber);
        }
        
        public System.Threading.Tasks.Task<string> getSerialSetLogAsync(string serialNumber) {
            return base.Channel.getSerialSetLogAsync(serialNumber);
        }
        
        public string getSerialSetLogLast(string serialNumber, int pRemote) {
            return base.Channel.getSerialSetLogLast(serialNumber, pRemote);
        }
        
        public System.Threading.Tasks.Task<string> getSerialSetLogLastAsync(string serialNumber, int pRemote) {
            return base.Channel.getSerialSetLogLastAsync(serialNumber, pRemote);
        }
        
        public string isInGestion(string user, string pass, string llave) {
            return base.Channel.isInGestion(user, pass, llave);
        }
        
        public System.Threading.Tasks.Task<string> isInGestionAsync(string user, string pass, string llave) {
            return base.Channel.isInGestionAsync(user, pass, llave);
        }
        
        public bool setPushNotification(string licencia, string nroMovil, string mensaje, string appID, string restApiKey) {
            return base.Channel.setPushNotification(licencia, nroMovil, mensaje, appID, restApiKey);
        }
        
        public System.Threading.Tasks.Task<bool> setPushNotificationAsync(string licencia, string nroMovil, string mensaje, string appID, string restApiKey) {
            return base.Channel.setPushNotificationAsync(licencia, nroMovil, mensaje, appID, restApiKey);
        }
    }
}
